wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705280924.690149
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.32.1
      8:
      - 5
      13: darwin-x86_64
input_perturbation:
  desc: null
  value: 0
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
variant:
  desc: null
  value: null
train_annotation_file:
  desc: null
  value: /Users/miav1/Desktop/university/2023/disseration/datasets/visual genome/data/train_coco_style.json
train_caption_file:
  desc: null
  value: /Users/miav1/Desktop/university/2023/disseration/datasets/visual genome/data/train_sg.json
image_folder:
  desc: null
  value: /Users/miav1/Desktop/university/2023/disseration/datasets/visual genome/data/images/VG_100K
val_annotation_file:
  desc: null
  value: /Users/miav1/Desktop/university/2023/disseration/datasets/visual genome/data/val_coco_style.json
val_caption_file:
  desc: null
  value: /Users/miav1/Desktop/university/2023/disseration/datasets/visual genome/data/val_sg.json
image_column:
  desc: null
  value: image
caption_column:
  desc: null
  value: captions
max_train_samples:
  desc: null
  value: null
output_dir:
  desc: null
  value: sd-model-layout2image-finetuned
cache_dir:
  desc: null
  value: cache/datasets
seed:
  desc: null
  value: null
resolution:
  desc: null
  value: 512
num_inference_steps:
  desc: null
  value: 100
train_batch_size:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 100
max_train_steps:
  desc: null
  value: 6370400
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 500
use_8bit_adam:
  desc: null
  value: false
allow_tf32:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: null
prediction_type:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: fp16
report_to:
  desc: null
  value: all
local_rank:
  desc: null
  value: -1
checkpointing_steps:
  desc: null
  value: 500
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
noise_offset:
  desc: null
  value: 0
validation_epochs:
  desc: null
  value: 1
tracker_project_name:
  desc: null
  value: layout2image-fine-tune
